### ISSUE TITLE
Hangar checking limits after and not before hangaring

### ISSUE THREAD

**Issue by xyqt** [Casimir255/QuantumHangar#39]
Encountering issues live on production for The Expanse Vanilla which runs a few plugins.
**Players are using !hangar save on grids that are over the servers allowed keen block limits(ex, grid with 20 grinders from 2 players, player keen block limit is 15). These players are then unable to !hangar load the grid back into the world.**
_This has cost us a huge labor cost on staff having to manually load these grids back into the world._ Is this a known bug where !hangar save does not perform a keen block limits check but !hangar load does?
We are unable to use the work around of not checking limits for !hangar load, as many players use it to bypass keen block limits restrictions.
Thank you so much in advance, QuantumHangar has been an amazing quality of life improvement.

**Comment by Casimir255** [comment]
Weird. I'll look at it tomorrow.

**Comment by Casimir255** [comment]
Alright so this is my conclusion:

1. **LimitIssue**: I 100% do limit checks on grid load. Saving grids that are over keens block limits or block limiter limits is something that I shouldn't need to even do. If you are able to build over your limits on the grid, then something is up with your limit system.
2. **TransferOnLoadIssue**  If you are using the "Transfer on Load" config which transfers all blocks to the person loading the grid, then yes, it will transfer and therefore put them over their limits. But that's nothing I can do to fix and is the downside of using hangar on two non-synced servers. (Identities saved in the blocks do not match and therefore would be random or owned by the enemy etc)

If your issue is with #2 which by this issue I would guess its keens vanilla limits, you may want to consider using Blocklimiter to physically limit the amount of those items not just by per player, but also per ship.

I hope those made sense. Let me know if you have any more questions that I could answer or if you want to give me some more insight on what you are using and the desired outcome.
